# Generated by Django 5.2.13 on 2026-04-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Insumo')),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('lt', 'Litros'), ('un', 'Unidades'), ('gr', 'Gramos'), ('ml', 'Mililitros')], default='un', max_length=2)),
                ('costo_unitario', models.DecimalField(decimal_places=2, help_text='Costo basado en la unidad de medida', max_digits=10, verbose_name='Costo Unitario')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Stock Físico Actual')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insumo Base',
                'verbose_name_plural': 'Insumos Base',
                'ordering': ['nombre'],
            },
        ),
    ]
