# Generated by Django 5.2.13 on 2026-05-18 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_venta_alter_insumo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientostock',
            options={'ordering': ['-fecha'], 'verbose_name': 'Movimiento de Stock', 'verbose_name_plural': 'Movimientos (Kardex)'},
        ),
        migrations.AlterField(
            model_name='ingredientereceta',
            name='cantidad_necesaria',
            field=models.DecimalField(decimal_places=3, help_text='Cantidad en la unidad de medida del insumo (ej: gramos o ml)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receta',
            name='nombre_producto',
            field=models.CharField(help_text='Nombre exacto que viene en el Excel de Fudo', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='archivo_origen',
            field=models.CharField(blank=True, help_text='Nombre del archivo CSV de Fudo', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientereceta',
            unique_together={('insumo', 'receta')},
        ),
    ]
