# Generated by Django 5.2.13 on 2026-05-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Rol')),
                ('porcentaje_am', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje Turno AM (%)')),
                ('porcentaje_pm', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje Turno PM (%)')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar este rol sin borrarlo')),
            ],
            options={
                'verbose_name': 'Regla de Distribución',
                'verbose_name_plural': 'Reglas de Distribución',
                'ordering': ['-porcentaje_am'],
            },
        ),
    ]
