# Generated by Django 5.2.13 on 2026-05-12 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propinas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('AM', 'Mañana'), ('PM', 'Tarde')], max_length=2)),
                ('propinas_sistema', models.IntegerField(default=0, help_text='Propinas registradas en FUDO')),
                ('efectivo', models.IntegerField(default=0, help_text='Propinas en efectivo')),
                ('cerrado', models.BooleanField(default=False, help_text='Si está cerrado, no se puede modificar')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha', 'tipo'],
                'unique_together': {('fecha', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='ParticipanteTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_asignado', models.IntegerField(blank=True, default=0, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='propinas.regladistribucion')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='propinas.turno')),
            ],
            options={
                'unique_together': {('turno', 'empleado')},
            },
        ),
    ]
